stages:
  ingest:
    cmd: PYTHONPATH=src python src/fraud_detection/data/ingest.py
    outs:
      - data/raw/creditcard.csv

  preprocess:
    cmd: PYTHONPATH=src python src/fraud_detection/data/preprocess.py
    deps:
      - data/raw/creditcard.csv
    outs:
      - data/processed/validated.csv

  features:
    cmd: PYTHONPATH=src python src/fraud_detection/features/build_features.py
    deps:
      - data/processed/validated.csv
    outs:
      - data/processed/features

  train:
    cmd: PYTHONPATH=src python -m fraud_detection.models.train
    deps:
      - src/fraud_detection/models/train.py
      - data/processed/features
    outs:
      - models
    metrics:
      - metrics/metrics.json
