stages:
  train:
    cmd: python src/fraud_detection/models/train.py data/processed/features models metrics
    deps:
      - src/fraud_detection/models/train.py
      - data/processed/features
    outs:
      - models
      - metrics
